name: Marcus hedges
favicon: null
layout_spectrum: 0.7292803751770407
typography_spectrum: 0.19467985234223306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.43805051827803254
  lightness: 0.5294372460339218
  saturation: 0.4733434955123812
  rhythmicContrast: 0.542355404002592
purpose: []
